package com.impulse.course;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "course")
@Entity
@Table(name = "course")
public class Course implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * course.id
   *
   * @mbggenerated Thu May 02 12:36:53 CST 2019
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @ApiModelProperty(hidden = true)
  private Integer id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * course.name
   *
   * @mbggenerated Thu May 02 12:36:53 CST 2019
   */
  private String name;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column course.id
   *
   * @return the value of course.id
   *
   * @mbggenerated Thu May 02 12:36:53 CST 2019
   */
  @ApiModelProperty(value = "course name", dataType = "string", example = "Chinese")
  @Column(unique = true)
  public Integer getId() {
    return this.id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column course.id
   *
   * @param id the value for course.id
   *
   * @mbggenerated Thu May 02 12:36:53 CST 2019
   */
  public void setId(final Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column course.name
   *
   * @return the value of course.name
   *
   * @mbggenerated Thu May 02 12:36:53 CST 2019
   */
  public String getName() {
    return this.name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column course.name
   *
   * @param name the value for course.name
   *
   * @mbggenerated Thu May 02 12:36:53 CST 2019
   */
  public void setName(final String name) {
    this.name = name == null ? null : name.trim();
  }
}
